### ISSUE TITLE
TypeError: route.split is not a function

### ISSUE THREAD

**Issue by tskravisankar** [ionic-team/ionic-plugin-deeplinks#243]
We have used ionic-native deeplinks in our project by using the below link.

https://ionicframework.com/docs/v3/native/deeplinks/

While clicking the link on browser, it shows the application and once the application is clicked, it open application. But it doesn't hit on any match or nomatch response. Instead of hitting anywhere, it throws the below error

**Error:**
![image](https://user-images.githubusercontent.com/26854917/105648632-81dfc100-5ed2-11eb-9e3b-aeb47cdfc9d9.png)
![image](https://user-images.githubusercontent.com/26854917/105648824-88226d00-5ed3-11eb-8e97-1635332ea146.png)

**Code used:**
![image](https://user-images.githubusercontent.com/26854917/105648758-26620300-5ed3-11eb-9c5e-821499c19f90.png)

    IonicModule.forRoot(MyApp,
      {
        //useHash: false, 
        tabsPlacement: 'bottom',
        //locationStrategy: 'path'
      },
      { component: TapPage, name: 'tapPage', segment: 'tap'},

**Version:**
    "ionic-angular": "3.9.2",
    "@ionic-native/core": "4.7.0",
    "@ionic-native/deeplinks": "^4.7.0",
    
**Ionic version:**
5.2.1

**node version:**
v10.15.1

Please provide us the solution to resolve this issue.

**Comment by newmesiss** [comment]
I have the same problem, any information?

**Comment by simion** [comment]
Same issue here

**Comment by Ivan981508** [comment]
I face this problem. Help

**Comment by Ivan981508** [comment]
I rolled back to the previous version and everything worked.
1. Remove the ios/android platform
2. npm uninstall @ionic-native/deeplinks
3. npm install @ionic-native/deeplinks@5.30.0

**Comment by inhand** [comment]
I'm having a similar issue. It looks like the code is expecting the route to be a string however its actually an Ionic Page object.

![Screenshot 2021-01-26 at 12 23 20](https://user-images.githubusercontent.com/4025613/105844645-77f0b780-5fd1-11eb-8708-608183e9d7ab.png)

Our code around the deeplink hasn't changed but this issue has suddenly appeared. I wonder if its changes around routing thats causing it to fail.

**Comment by pataar** [comment]
Looking at the recent PR's it seems it's caused by #191

**Comment by inhand** [comment]
@pataar yep thats exactly it.

**Comment by pataar** [comment]
Downgrading to version 1.0.19 seems to work.

**Comment by iMaheshwari** [comment]
I have following config -
"@ionic-native/core": "^4.20.0"
"@ionic-native/deeplinks": "^4.20.0"

"ionic-plugin-deeplinks": "1.0.19"

still facing this issue - "route.split is not a function"

Any solutions?

**Comment by inhand** [comment]
I had to go to 1.0.18 as I was still getting the issue with 1.0.18

**Comment by iMaheshwari** [comment]
Hi Mine got resolved with following config -
"@ionic-native/deeplinks":"^4.18.0"
"ionic-plugin-deeplinks":"^1.0.18"

**Comment by InfoMoreira** [comment]
**I left the same version for core and deeplink**
"@ionic-native/core": "4.3.2",
"@ionic-native/deeplinks": "^4.3.2",

**Comment by Snookmz** [comment]
This issue is related to one line of code that appears to be incorrect in deeplinks.js. as @pataar said it's from https://github.com/ionic-team/ionic-plugin-deeplinks/issues/243

The line in deeplinks.js:
var matchedParams = self.routeMatch(pathData, realPath);

should be:
var matchedParams = self.routeMatch(targetPath, realPath);

I have confirmed that this works as normal after the change.

If anyone is looking for a real quick and dirty fix then open up deeplinks.js and swap out that line.

**Comment by ziaurrehmanjutt** [comment]
> This issue is related to one line of code that appears to be incorrect in deeplinks.js. as @pataar said it's from #243
> 
> The line in deeplinks.js:
> var matchedParams = self.routeMatch(pathData, realPath);
> 
> should be:
> var matchedParams = self.routeMatch(targetPath, realPath);
> 
> I have confirmed that this works as normal after the change.
> 
> If anyone is looking for a real quick and dirty fix then open up deeplinks.js and swap out that line.

This is Also worked for me

**Comment by tskravisankar** [comment]
@Snookmz 

It worked. Thanks!

**Comment by tskravisankar** [comment]
> This issue is related to one line of code that appears to be incorrect in deeplinks.js. as @pataar said it's from #243
> 
> The line in deeplinks.js:
> var matchedParams = self.routeMatch(pathData, realPath);
> 
> should be:
> var matchedParams = self.routeMatch(targetPath, realPath);
> 
> I have confirmed that this works as normal after the change.
> 
> If anyone is looking for a real quick and dirty fix then open up deeplinks.js and swap out that line.

@Snookmz 

It worked. Thanks!

**Comment by jaimearrazola** [comment]
> This issue is related to one line of code that appears to be incorrect in deeplinks.js. as @pataar said it's from #243
> 
> The line in deeplinks.js:
> var matchedParams = self.routeMatch(pathData, realPath);
> 
> should be:
> var matchedParams = self.routeMatch(targetPath, realPath);
> 
> I have confirmed that this works as normal after the change.
> 
> If anyone is looking for a real quick and dirty fix then open up deeplinks.js and swap out that line.

This only removed the error but now its doesn't match any routes, always returns false when matching parts.length !== routeParts.length. I am pretty sure this is still plenty broken....

**Comment by proofles** [comment]
I have the same problem, any information?

**Comment by jaimearrazola** [comment]
> I have the same problem, any information?

If messing around with the versions of the plugin don't work (try to go at or below 1.0.18) then try Snookmz's solution for a quick fix. Since my routing however includes params the solution wasn't enough for me and I had to hard code the actual value of targetPath in the plugin to suit my needs.....

**Comment by proofles** [comment]
> > I have the same problem, any information?
> 
> If messing around with the versions of the plugin don't work (try to go at or below 1.0.18) then try Snookmz's solution for a quick fix. Since my routing however includes params the solution wasn't enough for me and I had to hard code the actual value of targetPath in the plugin to suit my needs.....

Thanks for reply. Could you please share with me your hard codes. I do not fully understand how to set targetPath.

**Comment by jaimearrazola** [comment]
> > > I have the same problem, any information?
> > 
> > 
> > If messing around with the versions of the plugin don't work (try to go at or below 1.0.18) then try Snookmz's solution for a quick fix. Since my routing however includes params the solution wasn't enough for me and I had to hard code the actual value of targetPath in the plugin to suit my needs.....
> 
> Thanks for reply. Could you please share with me your hard codes. I do not fully understand how to set targetPath.

Here you go, I commented it as best as I could. https://github.com/jaimearrazola/custom-deeplinks 
Please note this should only be a last resource attempt and you will need to reload this file manually every time you regenerate the platform

**Comment by proofles** [comment]
@jaimearrazola thank you very much.

I changed version from 1.0.22 to **1.0.20**, my problem solved.

**Comment by geshub** [comment]
Hi,
Would be great to have a fix for this as it breaks all deeplinks

**Comment by blackeagle1111** [comment]
> @jaimearrazola thank you very much.
> 
> I changed version from 1.0.22 to **1.0.20**, my problem solved.

what is your version for the following?
"@ionic-native/core"
"@ionic-native/deeplinks"

**Comment by proofles** [comment]
> > @jaimearrazola thank you very much.
> > I changed version from 1.0.22 to **1.0.20**, my problem solved.
> 
> what is your version for the following?
> "@ionic-native/core"
> "@ionic-native/deeplinks"

"@ionic-native/core": "^4.20.0"
"@ionic-native/deeplinks": "^4.20.0"

**Comment by blackeagle1111** [comment]
> > > @jaimearrazola thank you very much.
> > > I changed version from 1.0.22 to **1.0.20**, my problem solved.
> > 
> > 
> > what is your version for the following?
> > "@ionic-native/core"
> > "@ionic-native/deeplinks"
> 
> "@ionic-native/core": "^4.20.0"
> "@ionic-native/deeplinks": "^4.20.0"

Thank you!

**Comment by whitymighty** [comment]
I am facing this problem too, here is what I run:
"@ionic-native/core": "^5.31.1",
"@ionic-native/deeplinks": "^5.31.1",
"ionic-plugin-deeplinks": "^1.0.22"
I have tried all the wirkarounds mentioned above, almost every combination of versions, I still have the same problem
Also, I don't know if this could be of help, but in the console.log, the "route.split is not a function" becomes "TypeError: Cannot read property 'length' of undefined" after 2 seconds", that's until I click on the deeplink again

**Comment by mgreg89** [comment]
@whitymighty For me it was really crucial to not just downgrade, but really to remove and reinstall all platforms as the scripts in there won't get updated automatically.

**Comment by whitymighty** [comment]
> @whitymighty For me it was really crucial to not just downgrade, but really to remove and reinstall all platforms as the scripts in there won't get updated automatically.

I did that with every version/deeplink.js edit and still face the same problem

**Comment by mgreg89** [comment]
@whitymighty Last guess that I have, is to check the plugins folder after the downgrade to see if the downgrade was successful. Hope it helps!

**Comment by whitymighty** [comment]
@mgreg89 Sadly that also didn't work, thank you so much for trying tho.
here's a recap for everyone:
"ionic-plugin-deeplinks": "^1.0.20"
"@ionic-native/core": "5.20.0"
"@ionic-native/deeplinks": "5.20.0"

Deleted the node_module and plugins folders, deleted the platforms, edited the deeplink.js as @snookmz suggested, and I am still facing the same problem

**Comment by whitymighty** [comment]
Okay, so I figured out the problem. It turns out that ionic 4 does not support routing from the deeplink like: 
"this.deeplinks.routeWithNavController(this.navCtrl, {
  '/products/:productId': **_ProductPage_**
}).subscribe(match => {"
Importing the page to redirect to is apparently deprecated and causes the "route.split is not a function" error.
All I did was that I quoted the ionic pages's name.
Though to be I am not sure if toying around with the versions actually helped.
I hope this fixes the problem for whoever goes through the same. Peace

**Comment by ChristiaanScheermeijer** [comment]
#242 should fix this issue as well. Still waiting for it to be approved and merged. In the meanwhile, we're using this patch as a temporary fix.

**Comment by shradhac59** [comment]
> This issue is related to one line of code that appears to be incorrect in deeplinks.js. as @pataar said it's from #243
> 
> The line in deeplinks.js:
> var matchedParams = self.routeMatch(pathData, realPath);
> 
> should be:
> var matchedParams = self.routeMatch(targetPath, realPath);
> 
> I have confirmed that this works as normal after the change.
> 
> If anyone is looking for a real quick and dirty fix then open up deeplinks.js and swap out that line.

Hey  this is still not working for me , need help

**Comment by shradhac59** [comment]
> #242 should fix this issue as well. Still waiting for it to be approved and merged. In the meanwhile, we're using this patch as a temporary fix.

hey is this closed?

**Comment by blackevil2703** [comment]
What's the final fix? I see the same issue with updated plugin

**Comment by blackevil2703** [comment]
"@ionic-native/core": "5.0.0",
"@ionic-native/deeplinks": "^5.0.0",
plugin version ^1.0.18

fixed my issue

**Comment by geshub** [comment]
Any update on this issue ?

**Comment by FrancescoPaiola** [comment]
Any update on this?

**Comment by markwtaylor** [comment]
1.0.20 worked for me after I found that Ionic Build was using 1.0.22 although I had 1.0.20 specified in package.json. This was because my project did not have a package-lock.json included to make sure the exact version I installed was used.

**Comment by paulovelho** [comment]
as there is still no fix for this bug, I would like to share my temporary solution:

I had something like:
```
const deeplinkList = {
	'/products/all': ProductsComponent,
	'/product/:id': ViewProductComponent,
};

this.deeplinks.routeWithNavController(nav, deeplinkList)
	.subscribe(match => {}, nomatch => {
		console.error("nomatch for deeplink: ", nomatch);
	});
```

that I had to convert in something like:
```
const deeplinkList = {
	'/products/all': "ProductsComponent", // a string here will avoid that split error to be thrown.
	'/product/:id': "ViewProductComponent",
};

this.deeplinks.routeWithNavController(nav, deeplinkList)
	.subscribe(match => {
		const matchData = match['$link'];
		// matchData is now a object like:
	/*
		host: "products"
		path: "/all"
		queryString: ...
		scheme: "..."
		url: "..."
	*/
		// with this data I manually redirect to Products Component on my own rules in this function

	}, nomatch => {
		console.error("nomatch for deeplink: ", nomatch);
	});
```

**Comment by geshub** [comment]
It seems this fix was not merged in 1.0.23, how is it possible to use the plugin with this redirect bug ?

**Comment by mlynch** [comment]
Does someone have a PR for this? We can look at and merge it and get a new release out

**Comment by geshub** [comment]
> Does someone have a PR for this? We can look at and merge it and get a new release out

[https://github.com/ionic-team/ionic-plugin-deeplinks/pull/242](this seems to fix the bug)

**Comment by mlynch** [comment]
Out in 1.0.24 thanks
